# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-28 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('isadmin', models.BooleanField(default='False')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
