# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20171128_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='created',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='updated',
        ),
    ]
